### ISSUE TITLE
child_process: customFds option is deprecated, use stdio instead.

### ISSUE THREAD

**Issue by koenkarsten** [ging/fiware-pep-proxy#5]
When npm installing an fresh installation, the xml2json dependency throws the following error:
*child_process: customFds option is deprecated, use stdio instead.*

After this the terminal throws quite a bit of errors, I have listed them below:

<pre>
[device]:fi-ware-pep-proxy [username]$ npm install
-
> node-expat@2.1.4 install /Users/[username]/[company]/git/fi-ware-pep-proxy/node_modules/xml2json/node_modules/node-expat
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
../deps/libexpat/lib/xmltok.c:471:1: warning: missing
      field 'isName2' initializer
      [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:484:1: warning: missing
      field 'isName2' initializer
      [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:504:1: warning: missing
      field 'isName2' initializer
      [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:517:1: warning: missing
      field 'isName2' initializer
      [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:730:1: warning: missing
      field 'isName2' initializer
      [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:749:1: warning: missing
      field 'isName2' initializer
      [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:762:1: warning: missing
      field 'isName2' initializer
      [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:775:1: warning: missing
      field 'isName2' initializer
      [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:871:1: warning: missing
      field 'isName2' initializer
      [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:890:1: warning: missing
      field 'isName2' initializer
      [-Wmissing-field-initializers]
};
^
10 warnings generated.
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  LIBTOOL-STATIC Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
In file included from ../node-expat.cc:1:
../node_modules/nan/nan.h:318:13: error: no member named
      'New' in 'v8::String'
    return  _NAN_ERROR(v8::Exception::Error, errmsg);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:298:50: note: expanded from
      macro '_NAN_ERROR'
  ..._NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                 ~~~~~~~~~~~~^
../node_modules/nan/nan.h:322:5: error: no member named
      'ThrowException' in namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:303:11: note: expanded from
      macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg))...
      ~~~~^
../node_modules/nan/nan.h:322:5: error: no member named
      'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:303:26: note: expanded from
      macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg))...
                         ^~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:298:50: note: expanded from
      macro '_NAN_ERROR'
  ..._NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                 ~~~~~~~~~~~~^
../node_modules/nan/nan.h:327:9: error: no type named
      'ThrowException' in namespace 'v8'
    v8::ThrowException(error);
    ~~~~^
../node_modules/nan/nan.h:334:65: error: no member named
      'New' in 'v8::String'
  ...err = v8::Exception::Error(v8::String::New(msg));
                                ~~~~~~~~~~~~^
../node_modules/nan/nan.h:336:26: error: no member named
      'New' in 'v8::String'
    obj->Set(v8::String::New("code"), v8::Int32::...
             ~~~~~~~~~~~~^
../node_modules/nan/nan.h:336:65: error: too few
      arguments to function call, expected 2, have 1
  ...v8::Int32::New(errorNumber));
     ~~~~~~~~~~~~~~            ^
/Users/[username]/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:3: note: 
      'New' declared here
  static Local<Integer> New(Isolate* isolate, int...
  ^
In file included from ../node-expat.cc:1:
../node_modules/nan/nan.h:348:12: error: no member named
      'New' in 'v8::String'
    return _NAN_ERROR(v8::Exception::TypeError, errmsg);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:298:50: note: expanded from
      macro '_NAN_ERROR'
  ..._NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                 ~~~~~~~~~~~~^
../node_modules/nan/nan.h:352:5: error: no member named
      'ThrowException' in namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:303:11: note: expanded from
      macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg))...
      ~~~~^
../node_modules/nan/nan.h:352:5: error: no member named
      'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:303:26: note: expanded from
      macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg))...
                         ^~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:298:50: note: expanded from
      macro '_NAN_ERROR'
  ..._NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                 ~~~~~~~~~~~~^
../node_modules/nan/nan.h:356:12: error: no member named
      'New' in 'v8::String'
    return _NAN_ERROR(v8::Exception::RangeError, errmsg);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:298:50: note: expanded from
      macro '_NAN_ERROR'
  ..._NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                 ~~~~~~~~~~~~^
../node_modules/nan/nan.h:360:5: error: no member named
      'ThrowException' in namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:303:11: note: expanded from
      macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg))...
      ~~~~^
../node_modules/nan/nan.h:360:5: error: no member named
      'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:303:26: note: expanded from
      macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg))...
                         ^~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:298:50: note: expanded from
      macro '_NAN_ERROR'
  ..._NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                 ~~~~~~~~~~~~^
../node_modules/nan/nan.h:668:49: error: too few
      arguments to function call, single argument
      'isolate' was not specified
    v8::Local<v8::Object> obj = v8::Object::New();
                                ~~~~~~~~~~~~~~~ ^
/Users/[username]/.node-gyp/0.12.0/deps/v8/include/v8.h:2388:3: note: 
      'New' declared here
  static Local<Object> New(Isolate* isolate);
  ^
In file included from ../node-expat.cc:1:
../node_modules/nan/nan.h:669:14: error: no member named
      'NewSymbol' in 'v8::String'; did you mean
      'IsSymbol'?
    obj->Set(NanSymbol("callback"), fn);
             ^~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:159:38: note: expanded from
      macro 'NanSymbol'
#define NanSymbol(value) v8::String::NewSymbol(value)
                         ~~~~~~~~~~~~^
/Users/[username]/.node-gyp/0.12.0/deps/v8/include/v8.h:1379:8: note: 
      'IsSymbol' declared here
  bool IsSymbol() const;
       ^
In file included from ../node-expat.cc:1:
../node_modules/nan/nan.h:669:14: error: call to
      non-static member function without an object
      argument
    obj->Set(NanSymbol("callback"), fn);
             ^~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:159:38: note: expanded from
      macro 'NanSymbol'
#define NanSymbol(value) v8::String::NewSymbol(value)
                         ~~~~~~~~~~~~^~~~~~~~~
../node_modules/nan/nan.h:675:12: error: no member named
      'Dispose' in 'v8::Persistent<v8::Object,
      v8::NonCopyablePersistentTraits<v8::Object> >'
    handle.Dispose();
    ~~~~~~ ^
../node_modules/nan/nan.h:676:12: error: no member named
      'Clear' in 'v8::Persistent<v8::Object,
      v8::NonCopyablePersistentTraits<v8::Object> >'
    handle.Clear();
    ~~~~~~ ^
../node_modules/nan/nan.h:680:46: error: no member named
      'NewSymbol' in 'v8::String'; did you mean
      'IsSymbol'?
  ...NanSymbol("callback"))
     ^~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:159:38: note: expanded from
      macro 'NanSymbol'
#define NanSymbol(value) v8::String::NewSymbol(value)
                         ~~~~~~~~~~~~^
/Users/[username]/.node-gyp/0.12.0/deps/v8/include/v8.h:1379:8: note: 
      'IsSymbol' declared here
  bool IsSymbol() const;
       ^
fatal error: too many errors emitted, stopping now
      [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/node_expat/node-expat.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/[username]/[company]/git/fi-ware-pep-proxy/node_modules/xml2json/node_modules/node-expat
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-expat@2.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-expat@2.1.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/[username]/[company]/git/fi-ware-pep-proxy/npm-debug.log
</pre>

Here follows the *npm-debug.log*, for further details:


<pre>
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'info' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose config Skipping project config: /Users/[username]/.npmrc. (matches userconfig)
5 verbose stack Error: Invalid package.json
5 verbose stack     at /usr/local/lib/node_modules/npm/lib/view.js:79:30
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:51:40
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:97:49
5 verbose stack     at evalmachine.<anonymous>:265:20
5 verbose stack     at OpenReq.Req.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:141:5)
5 verbose stack     at OpenReq.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:61:22)
5 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:99:15)
6 verbose cwd /Users/[username]
7 error Darwin 14.3.0
8 error argv "node" "/usr/local/bin/npm" "info"
9 error node v0.12.0
10 error npm  v2.5.1
11 error Invalid package.json
12 error If you need help, you may report this error at:
12 error     <http://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
</pre>

**Comment by aalonsog** [comment]
Sorry but I cannot reproduce the issue
