### ISSUE TITLE
Wilma freeze with reply if token is invalid

### ISSUE THREAD

**Issue by caa06d9c** [ging/fiware-pep-proxy#54]
PEP version: 7.0.1 (not matter)
IDM version: 7.0.0

Sending correct token:
>pep_1    | 2018-08-21 16:34:38.135  - INFO: IDM-Client - Token in cache, checking timestamp...
>pep_1    | 2018-08-21 16:34:38.135  - INFO: Root - Access-token OK. Redirecting to app...

Sending incorrect token: 
>pep_1    | 2018-08-21 16:35:16.456  - INFO: IDM-Client - Checking token with IDM...
>pep_1    | 2018-08-21 16:35:16.908  - ERROR: IDM-Client - Error validating token. Proxy not authorized in keystone. Keystone authentication ...
>pep_1    | 2018-08-21 16:35:17.317  - ERROR: Server - Caught exception: SyntaxError: Unexpected token u

if token is valid, http return code is 200.
If token is invalid, session freeze.

**Comment by jmcanterafonseca** [comment]
@aalonsog any news about this?

**Comment by aalonsog** [comment]
Hi @jmcanterafonseca, we will take a look today. Apologies for the delay

**Comment by apozohue10** [comment]
Hi @caa06d9c, @jmcanterafonseca we have created a new release: 7.0.2. In this release if token is invalid the session doesn't freeze and returns http code 401.

**Comment by caa06d9c** [comment]
Image was  [rebuilded](https://hub.docker.com/r/fiware/pep-proxy/builds/b59vxjnkecadhcwnsovgpoh/)

`TypeError: Cannot read property 'enabled' of undefined
    at pep (/opt/fiware-pep-proxy/controllers/root.js:48:38)
    at Layer.handle [as handle_request] (/opt/fiware-pep-proxy/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/fiware-pep-proxy/node_modules/express/lib/router/route.js:137:13)
    at next (/opt/fiware-pep-proxy/node_modules/express/lib/router/route.js:131:14)
    at next (/opt/fiware-pep-proxy/node_modules/express/lib/router/route.js:131:14)
    at next (/opt/fiware-pep-proxy/node_modules/express/lib/router/route.js:131:14)
    at next (/opt/fiware-pep-proxy/node_modules/express/lib/router/route.js:131:14)
    at next (/opt/fiware-pep-proxy/node_modules/express/lib/router/route.js:131:14)
    at next (/opt/fiware-pep-proxy/node_modules/express/lib/router/route.js:131:14)
    at Route.dispatch (/opt/fiware-pep-proxy/node_modules/express/lib/router/route.js:112:3)`

**Comment by caa06d9c** [comment]
Image was [rebuilded](https://hub.docker.com/r/fiware/pep-proxy/builds/b59vxjnkecadhcwnsovgpoh/)
Wilma returns 401 if token is not authorized, thanks!
