### ISSUE TITLE
Cannot read property 'split' of undefined when trying to run application

### ISSUE THREAD

**Issue by michalrubaj** [ging/fiware-pep-proxy#92]
I followed the steps given in instruction and I've got following error regardless whether I try to run application by executing 'sudo node server' or 'docker run...'

`TypeError: Cannot read property 'split' of undefined
    at Object.<anonymous> (/home/user/Dokumenty/fiware/fiware-pep-proxy/config.js:70:59)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/Dokumenty/fiware/fiware-pep-proxy/server.js:1:78)
    at Module._compile (module.js:652:30)
`

**Comment by apozohue10** [comment]
There was a bug. Currently, it should be fixed!
